[project]
name = "django-to-do-list"
version = "0.1.0"
description = "To-do list Django web application."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "django>=5.1.6",
]
