# Generated by Django 5.1.6 on 2025-03-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(db_default=False, help_text='Whether the task has been completed.')),
                ('title', models.TextField(help_text='The title of the task. (e.g. "Do laundry")')),
                ('description', models.TextField(blank=True, help_text='A longer description of the task.')),
                ('due_date', models.DateTimeField(help_text='The date that the task is due for completion.', null=True)),
            ],
        ),
    ]
