# Generated by Django 5.1.6 on 2025-03-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='The date and time at which the task is due for completion.', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(help_text='The title of the task. (e.g. "Do laundry")', unique=True),
        ),
    ]
